# Generated by Django 6.0.4 on 2026-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricealert",
            name="target_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
